US16-Users Reactions
UB-ES-2018/faceduck pull request #126
Opened 2018-11-09 01:15 UTC by Xexio15

Ja esta, a falta de revisio, la part de backend de Reactions, es pot afegir una reaction, amb POST  es crea la reaction o s'actualitza en el cas que l'usuari la canvii a una altra, es poden eliminar Reactions amb DELETE.
A més he afegit un camp que mante un comptador de les reactions que te un post per si fos necessari per al frontend i ja tenir-ho precalculat. A veure com ho veieu.
També he actualitzat la Spec ja que el esquema de Post s'ha ampliat.

2018-11-09 14:08 UTC, ifrins requested changes
Té bona pinta. Hi ha un parell marcades que hauries de fer-hi una ullada. Ja s'ha fet merge de la PR dels tests automàtics d'API, així que si tens ocasió també estaria guai que n'hi hagués ja d'això.

2018-11-09 14:08 UTC, ifrins commented on backend/app/faceduck/views/api.py
> +    except FaceduckError as e:
sembla, a priori, que falta un `KeyError` si no hi ha reaction que s'hauria de controlar

2018-11-09 14:08 UTC, ifrins commented on backend/app/faceduck/views/mappers.py
> +            print(rc,file=sys.stderr)
sobra el logging

2018-11-10 07:49 UTC, dabytmc requested changes

2018-11-10 07:49 UTC, dabytmc commented on backend/app/faceduck/views/api.py
> +    except KeyError:
El KeyError iba en la otra funcion no aquí, no?

2018-11-10 12:50 UTC, Xexio15 commented on backend/app/faceduck/views/api.py
> +    except KeyError:
Uf cierto, nose que se me paso por la cabeza

2018-11-10 15:58 UTC, ifrins approved these changes
Té bona pinta. El commit de merge d'una branca de FE que has posat sobra, no?

2018-11-10 16:06 UTC, ifrins commented
Ja he vist la història del merge, l'he tret, arreglao! 👍

2018-11-10 16:09 UTC, 3nr1c approved these changes
lgtm

2018-11-10 16:49 UTC, merged