US20 Create Groups Backend
UB-ES-2018/faceduck pull request #148
Opened 2018-11-16 19:26 UTC by Xexio15

Grupos funcionales en Backend segun lo hablado con @maimg. Deberian estar todas las funciones necesarias para Frontend, si falta alguna cosa la añado. Api spec definida + Tests

2018-11-17 16:32 UTC, maimg commented
Yo lo veo bien, aunque me lo tendre que volver a revisar cuando este la API spec. 
La duda que tengo es si te deja crear grupo sin imagen o obligatoriamente le tienes que pasar una. 
En el cado Facebook cuando te da a seleccionar imagen te pone unos iconitos de muestra.

2018-11-17 17:30 UTC, Xexio15 commented
`image-url` no es obligatorio asi que puedes crearlo sin imagen

2018-11-18 12:22 UTC, maimg commented on docs/API_Specification.md
> +    "title": "Create post success",
No deberia ser create group success?

2018-11-18 12:26 UTC, maimg commented on docs/API_Specification.md
> +
Faltan cosas por rellenar no

2018-11-18 12:32 UTC, maimg commented
Faltarian cositas a rellenar en las Request de la API Spec, te he puesto un par de comments y más abajo de estos hay otras Requests a las que les faltan cosas.

2018-11-18 12:49 UTC, Xexio15 commented on docs/API_Specification.md
> +
No acabo de ver que es lo que falta

2018-11-18 12:50 UTC, Xexio15 commented on docs/API_Specification.md
> +    "title": "Create post success",
Si, puede que haya algunos errores de estos en la Spec

2018-11-24 15:25 UTC, dabytmc requested changes

2018-11-24 15:25 UTC, dabytmc commented on backend/app/faceduck/views/api.py
> +    name = request.json["name"]
Falta un except KeyError

2018-11-24 15:25 UTC, dabytmc commented on backend/app/faceduck/views/api.py
> +    text = request.json["text"]
KeyError

2018-11-24 15:25 UTC, dabytmc commented on backend/app/faceduck/views/api.py
> +    admin = request.json["admin"]
KeyError

2018-11-24 15:25 UTC, dabytmc commented on backend/app/faceduck/views/mappers.py
> +            print(getattr(group,attr),file=sys.stderr)
Print

2018-11-25 16:49 UTC, dabytmc approved these changes

2018-11-25 20:43 UTC, merged