[WIP] Us 28 login log
UB-ES-2018/faceduck pull request #153
Opened 2018-11-23 17:07 UTC by FlorenzoC

First login log

2018-11-26 08:56 UTC, ifrins reviewed
S'haurien de fer tests abans de fer merge.

2018-11-27 16:38 UTC, dabytmc requested changes
Has de posar el test abans del shutdown API, sino la API esta apagada quan intentes fer el test.

2018-11-27 21:28 UTC, dabytmc approved these changes

2018-11-27 21:31 UTC, 3nr1c approved these changes

2018-11-27 21:48 UTC, merged