Close #3 Us 01 first visual design
UB-ES-2018/faceduck pull request #31
Opened 2018-09-30 18:41 UTC by IvanSevilla

Did you like the color and the buttons? We need Bootstrap enabled in the Project to make it more beautiful, now is a little bit ugly. I made a Markdown to keep the color pallet.

2018-09-30 21:09 UTC, 3nr1c requested changes

2018-09-30 21:09 UTC, 3nr1c commented on frontend/app/src/views/Homepage.vue
> +        <button id='but_sign' href="/login">Log in</button>
Más que id="but_sign", lo ideal sería ponerlo en una clase (.but_sign). Yo pondría además los nombres enteros, sign_button o algo así, que luego cuesta mantener el código.

2018-09-30 21:40 UTC, IvanSevilla commented on frontend/app/src/views/Homepage.vue
> +        <button id='but_sign' href="/login">Log in</button>
Lo he puesto así, porque no sabía cómo hacerlo. Pero si, esa sería la idea. Lo de la clase no se como abordarlo

2018-10-01 09:08 UTC, 3nr1c approved these changes
En mi rama de estructura he cambiado los nombres de los componentes para seguir la convención MínimoDosNombres.vue, cuando haga merge de lo mío ya lo arreglaré. Todo bien :shipit:

2018-10-01 12:48 UTC, closed without merging