Primer API Implementation
UB-ES-2018/faceduck pull request #39
Opened 2018-10-03 20:00 UTC by FlorenzoC

Dieume què falta i què està malament please

2018-10-03 20:12 UTC, ifrins requested changes

2018-10-03 20:12 UTC, ifrins commented on backend/app/faceduck/core/signup.py
> +		return Response({'error-message':'Username used'}, status=400)
Jo enlloc de fer returns de `Response` d'algo, el que faria seria tirar excepcions amb l'error (en pots fer una excepció per cada Error message), així es una mica mes type-safe. D'altre banda, també, així no acobles tant la lògica de negoci amb el fet que estiguis fent una API.

2018-10-03 20:12 UTC, ifrins commented on backend/app/faceduck/core/signup.py
> +def validateSignup(user, email, password, name, surname, birthday, gender):
Aquest mètode te un mal nom perque no només valida, sinó que crea. Jo canviaria el nom

2018-10-03 20:12 UTC, ifrins commented on backend/app/faceduck/core/signup.py
> +	return Response(status=204)
Ídem com a dalt. Pots retornar el nou user (tot i que despres no en facis res, per exemple).

2018-10-03 20:12 UTC, ifrins commented on backend/app/faceduck/core/signup.py
> +from flask import Response
Els dos imports últims jo crec que sobren

2018-10-03 20:12 UTC, ifrins commented on backend/app/faceduck/views/api.py
> +		resp = {'error-id': '400', 'error-message': 'Invalid data submitted'}
Crec que es podria convertir en una exception (o similars) en funció de com ho has fet i així reutilitzes codi (i no dupliques)

2018-10-04 15:07 UTC, 3nr1c requested changes

2018-10-04 15:07 UTC, 3nr1c commented on backend/app/faceduck/core/signup.py
> +	newUser = User(username=user, email=email, password=password, name=name, surname=surname, birthday=birthday, gender=gender)
**S'hauria d'encriptar (hash) la password abans de guardar-la**

2018-10-08 14:45 UTC, ifrins requested changes

2018-10-08 14:45 UTC, ifrins commented on backend/app/faceduck/core/signup.py
> +	newUser = User(username=user, email=email, password=password, name=name, surname=surname, birthday=birthday, gender=gender)
Aquí, a banda, s'ha de setejar el id del usuari (un UUID es bien)

2018-10-08 14:45 UTC, ifrins commented on backend/app/faceduck/core/signup.py
> +	try{
no compila 👎

2018-10-08 19:13 UTC, ifrins requested changes

2018-10-08 19:13 UTC, ifrins commented on backend/app/faceduck/core/signup.py
> +def createUser(id, user, email, password, name, surname, birthday, gender):
jo el UUID el crearia dins.

2018-10-08 19:13 UTC, ifrins commented on backend/app/faceduck/core/signup.py
> +	newUser = User(meta='id': id},  username=user, email=email, password=password, name=name, surname=surname, birthday=birthday, gender=gender)
![](https://media.giphy.com/media/3o7aD3BJA8vIGVaMw0/giphy.gif)

2018-10-08 19:14 UTC, ifrins requested changes

2018-10-08 19:14 UTC, ifrins commented on backend/app/faceduck/core/signup.py
> +	newUser = User(meta='id': id},  username=user, email=email, password=password, name=name, surname=surname, birthday=birthday, gender=gender)
I la PWD continua sense estar encriptada (hash)

2018-10-08 19:14 UTC, ifrins commented on backend/app/faceduck/core/signup.py
> +from faceduck.models.user import User
I hauries de tornar a fer merge de la branca US-01 a la teva branca per tenir el model

2018-10-09 06:41 UTC, FlorenzoC commented
Cierro PR ya que he puesto una nueva con el merge de US-01 hecho

2018-10-09 06:41 UTC, closed without merging