US-03 Text post API definition
UB-ES-2018/faceduck pull request #46
Opened 2018-10-08 21:06 UTC by dabytmc

Create and get a text post API requests definitions.

Fixes #22

2018-10-09 08:19 UTC, IvanSevilla reviewed
A mi me parece bien, alguien tiene alguna sugerencia de mejora?

2018-10-09 08:37 UTC, IvanSevilla approved these changes

2018-10-09 09:26 UTC, Xexio15 approved these changes

2018-10-09 16:48 UTC, 3nr1c requested changes
no compila

2018-10-09 16:48 UTC, 3nr1c commented on docs/API_Specification.md
> +    "created-at": "12-01-2018, 03:45:34"
no compila

2018-10-10 08:24 UTC, 3nr1c approved these changes

2018-10-10 08:25 UTC, merged