Us 01 api definition
UB-ES-2018/faceduck pull request #49
Opened 2018-10-09 06:39 UTC by FlorenzoC

Fets canvis i merge

2018-10-09 06:46 UTC, 3nr1c requested changes
Falta el hashing de la password

2018-10-09 13:06 UTC, ifrins requested changes

2018-10-09 13:06 UTC, ifrins commented on backend/app/faceduck/core/signup.py
> +		newUser = User({meta='id': uuid.uuid4()},  username=user, email=email, password=password, name=name, surname=surname, birthday=birthday, gender=gender)
La validació de unicitat i tot plegat?

2018-10-09 16:44 UTC, IvanSevilla approved these changes
Lo veo correcto

2018-10-11 07:23 UTC, 3nr1c approved these changes
## Abans de fer merge, prova-ho. Si no saps com fer-ho, fes merge i s'encarregarà algú altre de fer el test (veure slack)

2018-10-11 17:23 UTC, 3nr1c commented
# Tanco per canvi a una altra PR (mala praxis)

2018-10-11 17:23 UTC, closed without merging