Us6 image uploader component
UB-ES-2018/faceduck pull request #79
Opened 2018-10-16 14:41 UTC by 3nr1c

This closes #60.

2018-10-16 20:13 UTC, maimg approved these changes
Debo decir que se ve un poco rara la imagen porque no hay un resize o algo asi y si la imagen es grande se ve muy grande dentro del post.
A parte de esto, lo veo correcto

2018-10-17 09:46 UTC, dabytmc requested changes

2018-10-17 09:46 UTC, dabytmc commented on backend/app/faceduck/views/upload.py
> +import sys
Unused import

2018-10-17 09:58 UTC, dabytmc approved these changes

2018-10-17 09:58 UTC, merged

2018-10-17 11:01 UTC, IvanSevilla reviewed
Lo que comentaste ayer sobre no usar localStorage (lo que yo hice), tendremos que mirarlo. Por otra parte maite tiene razón, tenemos que tener en cuenta el tamaño de las imagenes, para que siempre