US-09-Connect Users
UB-ES-2018/faceduck pull request #94
Opened 2018-10-19 17:47 UTC by Xexio15

He creat el model de Friendship que connecta als Users segons la idea que he parlat amb @ifrins, he implementat:  
- La creacio de les amistads
- Poder actualitzar les amistads 
- Poder fer un get de totes les amistads d'un usuari

També he afegit la info a la API. 
  
Espero que no sigui molt desastre el codi qualsevol cosa a canviar m'ho dieu sense problemes que segurament hi hagi més d'una cosa millorable. Alguna funcionalitat que veieu que trobeu a faltar o si en els noms dels endpoints veieu alguna opcio més correcte els modificare perque no sabia ben be com organitzar-ho.

PD: He provat tot amb el Postman y funciona

2018-10-20 09:43 UTC, 3nr1c requested changes
Estaria bé fusionar les dues rutes de /user/friend i /user/friendship, per dos motius:
1. És força confús, per com es diuen no hi ha manera de distingir-les
2. Una és de creació i l’altra d’update, si no m’equivoco. Per tant, la manera típica de tractar-ho seria que la de creació anés amb el mètode POST i l’altra amb el mètode UPDATE o PUT (ara no recordo quin)

A part, entenc que els estats possibles són “pending” i “friends”? Posa-ho a la documentació, ja que "state" no és un string qualsevol sino una mena d'_enum_.

Necessitaria un endpoint que fos amb el mètode DELETE, que esborrés la friendship fos quin fos l’estat

2018-10-20 11:23 UTC, 3nr1c approved these changes
lgtm :+1: :+1:

2018-10-20 13:53 UTC, ifrins reviewed
Té molt bona pinta! He trobat un major nitpick, que no estic segur si està fet on purpose o és un oversight. La resta tot bé!

2018-10-20 13:53 UTC, ifrins commented on backend/app/faceduck/views/api.py
> +        user_id = request.json["user_id"]
aquí hi ha un potencial de impersonació molt gran. La request es autenticada (per tant, l'està fent en concret un usuari) i aquí dexiem a l'usuari que ens digui que és un altre. Si importes el `current_user` de `flask_jwt_extended` [docs](https://flask-jwt-extended.readthedocs.io/en/latest/complex_objects_from_token.html) tindràs l'objecte `User` del user que està autenticat.

2018-10-20 13:53 UTC, ifrins commented on backend/app/faceduck/views/api.py
> +        user_id = request.json["user_id"]
idem

2018-10-20 13:53 UTC, ifrins commented on backend/app/faceduck/views/api.py
> +        user_id = request.json["user_id"]
idem

2018-10-20 13:53 UTC, ifrins commented on docs/API_Specification.md
> +        "user_id": {"type": "string"},
pel comentat a dalt, en totes les tres requests sobraria que es passes el `user_id`.

2018-10-20 17:05 UTC, dabytmc reviewed
He encontrado algunos typos o tonterias en la spec. Faltan por señalar algún titulo de json schema que también está mal, si puedes revisalos todos.
A parte de lo de docu, he marcado canviar el return del DELETE a un 204 sin contenido como en singup, si quereis lo hablamos por Slack a ver que os parece.

2018-10-20 17:05 UTC, dabytmc commented on docs/API_Specification.md
> +`200 Ok`
Tal vez se podria mandar un 204 No content sin json ni nada para evitar un body que sea solo una confirmación, como hicimos en el Signup? Si quereis lo hablamos por slack antes.

2018-10-20 17:05 UTC, dabytmc commented on docs/API_Specification.md
> +        "user_id": {"type": "string"},
Sobra la coma final

2018-10-20 17:05 UTC, dabytmc commented on docs/API_Specification.md
> +                 }
La tabulación de estas tres lineas es diferente al resto

2018-10-20 17:05 UTC, dabytmc commented on docs/API_Specification.md
> +    "title": "Create post error",
Typo en el título

2018-10-20 17:05 UTC, dabytmc commented on docs/API_Specification.md
> +    "title": "Create friendship",
Typo en el título

2018-10-20 17:05 UTC, dabytmc commented on docs/API_Specification.md
> +    "title": "Create friendship success",
Typo en el título

2018-10-20 17:05 UTC, dabytmc commented on docs/API_Specification.md
> +        "user_id": {"type": "string"},
Sobra la coma final

2018-10-20 17:14 UTC, ifrins approved these changes

2018-10-21 11:58 UTC, dabytmc approved these changes

2018-10-21 12:24 UTC, merged